I'm experimenting with creating a hard link from the install/etc/ directory

diff --git a/doc/build b/doc/build
--- a/doc/build
+++ b/doc/build
@@ -79,10 +79,10 @@ case "$mode" in
     cd $base/$module        || exit
     ppremake                || exit
     make uninstall install  || exit
-	modules_ppremake=""
-	modules_clean=""
-	modules_uninstall=""
-	modules_install=""
+    modules_ppremake=""
+    modules_clean=""
+    modules_uninstall=""
+    modules_install=""
     ;;
 ( quick )
     cd $base/$module/src/$3 || exit
@@ -90,71 +90,71 @@ case "$mode" in
     cd $base/$module        || exit
     make install            || exit
     wantGenPy=0
-	modules_ppremake=""
-	modules_clean=""
-	modules_uninstall=""
-	modules_install=""
+    modules_ppremake=""
+    modules_clean=""
+    modules_uninstall=""
+    modules_install=""
     ;;
 ( new )
-	# ...build the newest version of the code:
-	echo -e "\nUpdating cvs\n"
-	cd "$base"   || exit
-	./cvs_update || exit
-	cd "$base"   || exit
-	# This next command is allowed to fail (no || exit):
-	echo -e "\nBuilding tags file\n"
-	ctags -nR -h '+.I' --langmap='c:+.I' -h '+.T' --langmap='c:+.T' --fields=fmisS
-	modules_ppremake=$modules
-	modules_clean="direct $modules_clean"
-	modules_uninstall=$modules
-	modules_install=$modules
-	;;
+    # ...build the newest version of the code:
+    echo -e "\nUpdating cvs\n"
+    cd "$base"   || exit
+    ./cvs_update || exit
+    cd "$base"   || exit
+    # This next command is allowed to fail (no || exit):
+    echo -e "\nBuilding tags file\n"
+    ctags -nR -h '+.I' --langmap='c:+.I' -h '+.T' --langmap='c:+.T' --fields=fmisS
+    modules_ppremake=$modules
+    modules_clean="direct $modules_clean"
+    modules_uninstall=$modules
+    modules_install=$modules
+    ;;
 ( ppremake )
     wantGenPy=0
-	modules_ppremake=$modules
-	modules_clean=""
-	modules_uninstall=""
-	modules_install=""
-	;;
+    modules_ppremake=$modules
+    modules_clean=""
+    modules_uninstall=""
+    modules_install=""
+    ;;
 ( clean )
     wantGenPy=0
-	modules_ppremake=$modules
-	modules_clean=$modules
-	modules_uninstall=""
-	modules_install=""
-	;;
+    modules_ppremake=$modules
+    modules_clean=$modules
+    modules_uninstall=""
+    modules_install=""
+    ;;
 ( uninstall )
     wantGenPy=0
-	modules_ppremake=$modules
-	modules_clean=""
-	modules_uninstall=$modules
-	modules_install=""
-	;;
+    modules_ppremake=$modules
+    modules_clean=""
+    modules_uninstall=$modules
+    modules_install=""
+    ;;
 ( install )
-	modules_ppremake=$modules
-	modules_clean=""
-	modules_uninstall=$modules
-	modules_install=$modules
-	;;
+    modules_ppremake=$modules
+    modules_clean=""
+    modules_uninstall=$modules
+    modules_install=$modules
+    ;;
 ( "" )
-	modules_ppremake=$modules
-	# Some modules are small enough that we clean them for good measure:
-	modules_clean="direct $modules_clean"
-	modules_uninstall=$modules
-	modules_install=$modules
-	;;
+    modules_ppremake=$modules
+    # Some modules are small enough that we clean them for good measure:
+    modules_clean="direct $modules_clean"
+    modules_uninstall=$modules
+    modules_install=$modules
+    ;;
 ( genpy )
     wantGenPy=1
-	modules_ppremake=""
-	modules_clean=""
-	modules_uninstall=""
-	modules_install=""
-	;;
+    modules_ppremake=""
+    modules_clean=""
+    modules_uninstall=""
+    modules_install=""
+    ;;
 ( * )
-	echo -e "\nThat mode is not recognized ($mode)"
-	echo "$usage"
-	exit 1
-	;;
+    echo -e "\nThat mode is not recognized ($mode)"
+    echo "$usage"
+    exit 1
+    ;;
 esac
 
 echo "    modules_ppremake  =$modules_ppremake"
@@ -163,31 +163,39 @@ echo "    modules_uninstall =$modules_uninstall"
 echo "    modules_install   =$modules_install"
 
 for i in $modules_ppremake; do
-	echo -e "\nStarting Ppremake of $i\n"
-	cd "$base/$i"            || exit
-	ppremake $ppremake_args  || exit
+    echo -e "\nStarting Ppremake of $i\n"
+    cd "$base/$i"            || exit
+    ppremake $ppremake_args  || exit
 done
 for i in $modules_clean; do
-	echo -e "\nStarting Clean of $i\n"
-	cd "$base/$i"   || exit
-	make clean      || exit
+    echo -e "\nStarting Clean of $i\n"
+    cd "$base/$i"   || exit
+    make clean      || exit
 done
 for i in $modules_uninstall; do
-	echo -e "\nStarting Uninstall of $i\n"
-	cd "$base/$i"   || exit
-	make uninstall  || exit
+    echo -e "\nStarting Uninstall of $i\n"
+    cd "$base/$i"   || exit
+    make uninstall  || exit
 done
 for i in $modules_install; do
-	echo -e "\nStarting Install (build) of $i\n"
-	cd "$base/$i"    || exit
-	make install   || exit
+    echo -e "\nStarting Install (build) of $i\n"
+    cd "$base/$i"   || exit
+    make install    || exit
 done
+
+cd "$base"
 
 if (($wantGenPy)); then
     # Generate Python code:
     echo "Generating Python/C++ interface code"
     #cd $base || exit
     genPyCode || exit
+fi
+
+if [ ! -f "$INSTALL_DIR/etc/config.prc" -a -f "$HOME/config.prc" ]; then
+    echo ""
+    echo "A .prc file was found at '$HOME/config.prc' creating a hard link from '$INSTALL_DIR/etc/'"
+    ( cd "$INSTALL_DIR/etc" && ln "$HOME/config.prc" . );
 fi
 
 echo "done"
